In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [2]:
saper = pd.DataFrame()
saper['experience'] = [6.3,6.3,5,2,7,3,10,11]
saper['test_score(out of 10)'] = [8,8,6,10,9,7,7.85,7]
saper['interview_score(out of 10)'] = [9,6,7,10,6,10,7,8]
saper['Salary'] = [50000,45000,60000,65000,70000,62000,72000,80000]
saper

experience  test_score(out of 10)  interview_score(out of 10)  Salary
0         6.3                   8.00                           9   50000
1         6.3                   8.00                           6   45000
2         5.0                   6.00                           7   60000
3         2.0                  10.00                          10   65000
4         7.0                   9.00                           6   70000
5         3.0                   7.00                          10   62000
6        10.0                   7.85                           7   72000
7        11.0                   7.00                           8   80000

In [3]:
x = saper.drop('Salary', axis=1)
y = saper['Salary']

In [4]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.4, random_state=42)
X_train

experience  test_score(out of 10)  interview_score(out of 10)
2         5.0                   6.00                           7
4         7.0                   9.00                           6
3         2.0                  10.00                          10
6        10.0                   7.85                           7

In [5]:
model = LinearRegression()

In [9]:
reg= model.fit(X_train, y_train)

In [11]:
reg.score(X_train, y_train)

1.0

In [12]:
reg.coef_

array([1534.90328007, 2338.09924306,   84.10428932])

In [13]:
reg.intercept_

37708.1581160639

In [46]:
test1 = pd.DataFrame()
test1['experience'] = [2]
test1['test_score(out of 10)'] = 9
test1['interview_score(out of 10)'] = 6

experience  test_score(out of 10)  interview_score(out of 10)
0           2                      9                           6

In [48]:
test2 = pd.DataFrame()
test2['experience'] = [12]
test2['test_score(out of 10)'] = 10
test2['interview_score(out of 10)'] = 10
test2

experience  test_score(out of 10)  interview_score(out of 10)
0          12                     10                          10

In [51]:
reg.predict(test1)

array([62325.48359966])

In [52]:
reg.predict(test2)

array([80349.03280067])